format = """
$directory\
$git_branch\
$git_status\
$conda\
$cmd_duration\
$line_break\
$character"""

[cmd_duration]
min_time = 0
show_milliseconds = true

[directory]
truncate_to_repo = false
truncation_length = 6

